---
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "blocked"
  color: "d73a4a"
  description: "This item is blocked/relies on something else being done to be completed"
- name: "dependencies"
  color: "0052cc"
  description: "Pull requests that update a dependency file"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a22eef"
  description: "New feature or request"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "invalid"
  color: "e6e6fa"
  description: "This doesn't seem right"
- name: "meta"
  color: "ffffff"
  description: "Changes that aren't directly related to any source code"
- name: "question"
  color: "cc317c"
  description: "Further information is needed"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
